---
# RECORDER SETTINGS:
# ===
# The threshold at which the mic will pick up sound (turn up for noisy areas)
energy_threshold: 600
# The sampling rate for microphone audio (default is 16000)
sampling_rate: 16000
# Our frame width in seconds (i.e. how often we run audio through the recognizer)
frame_width: 1.0

# TRANSLATOR SETTINGS:
# ===
# -- Settings for whisper_local
# The name of the local whisper model to use (note: large defaults to large-v2)
# Choices: ["tiny", "base", "small", "medium", "large"]
model_name: medium
# The language of input (not required for api whisper)
# Choices: [Afrikaans, Arabic, Armenian, Azerbaijani, 
# Belarusian, Bosnian, Bulgarian, Catalan, Chinese, 
# Croatian, Czech, Danish, Dutch, English, Estonian, 
# Finnish, French, Galician, German, Greek, Hebrew, 
# Hindi, Hungarian, Icelandic, Indonesian, Italian, 
# Japanese, Kannada, Kazakh, Korean, Latvian, 
# Lithuanian, Macedonian, Malay, Marathi, Maori, 
# Nepali, Norwegian, Persian, Polish, Portuguese, 
# Romanian, Russian, Serbian, Slovak, Slovenian, 
# Spanish, Swahili, Swedish, Tagalog, Tamil, Thai, 
# Turkish, Ukrainian, Urdu, Vietnamese, and Welsh]
input_language: English

# POLICY SETTINGS:
# ===
# The policy to use for translation
# Choices: 
#   - "greedy": speak as soon as the translation is ready (min latency)
#   - "offline": speaks only after phrase_timeout has elapsed (max accuracy)
#   - "confidence": speaks as soon as confidence is above a threshold
#   - "consensus": speaks when two consecutive translations match
policy: consensus
# Threshold for the consensus policy (gamma)
# Translations will be spoken if segments from two consecutive passes have
# Levenshtein distance ratio of greater than consensus_threshold
# (higher = more accurate but slower, lower = faster but less accurate)
consensus_threshold: 0.9
# Threshold for the confidence policy (alpha)
# Translations will be spoken if chunks have confidence > confidence_threshold
# (higher = more accurate but slower, lower = faster but less accurate) 
confidence_threshold: 0.7
# Threshold for considering a segment to be a "silent" segment.
# Segments above this threshold will not be spoken regardless of policy
no_speech_threshold: 0.9

# VOCALIZER SETTINGS:
# ===
# -- Settings for elevenlabs
# The amount we will optimize the streaming latency 
# Ranges from 0 (default, no latency optimization) to 4 (max latency but low quality)
# (see: https://docs.elevenlabs.io/api-reference/text-to-speech#query)
optimize_streaming_latency: 3
# The stability of the output from 0 to 1 (i.e. how much will prosody fluctuate)
# and the similarity boost from 0 to 1 (i.e. how much does prev speech influence current)
# (see: https://docs.elevenlabs.io/api-reference/text-to-speech#body)
stability: 0.5
similarity_boost: 0.5