---
# RECORDER SETTINGS:
# ===
# The threshold at which the mic will pick up sound (turn up for noisy areas)
energy_threshold: 600
# Our frame width in seconds (i.e. how often we run audio through the recognizer)
frame_width: 1.0
# How much silence must elapse before we clear the frame buffer in seconds
phrase_timeout: 2.0
# The amount of overlap we accept between segments 
# (higher = more likely repetition, lower = more likely to miss phrases)
overlap_tolerance: 2.0